# Generated by Django 4.2.7 on 2023-12-05 17:48

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_alter_course_name_alter_subject_course_and_more'),
        ('users', '0002_alter_user_options_remove_user_username_user_avatar_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateTimeField(blank=True, default=datetime.datetime(2023, 12, 5, 17, 48, 22, 836043, tzinfo=datetime.timezone.utc), null=True, verbose_name='дата оплаты')),
                ('payment_amount', models.IntegerField(default=None, max_length=10, verbose_name='сумма платежа')),
                ('payment_method', models.CharField(choices=[(1, 'transfer'), (2, 'cash')], default=1)),
                ('paid_course', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='project.course', verbose_name='оплаченный курс')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'Платеж',
                'verbose_name_plural': 'Платежи',
            },
        ),
    ]
