# Generated by Django 4.2.7 on 2023-12-05 17:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_amount',
            field=models.IntegerField(default=None, verbose_name='сумма платежа'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 12, 5, 17, 48, 53, 968205, tzinfo=datetime.timezone.utc), null=True, verbose_name='дата оплаты'),
        ),
    ]
