# Generated by Django 4.2.7 on 2023-12-07 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_owner_alter_payment_payment_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='owner',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
