# Generated by Django 4.2.7 on 2023-12-07 20:54

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0007_alter_subject_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='владелец'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateTimeField(blank=True, default=datetime.datetime(2023, 12, 7, 20, 54, 50, 227636, tzinfo=datetime.timezone.utc), null=True, verbose_name='дата оплаты')),
                ('payment_amount', models.IntegerField(default=None, verbose_name='сумма платежа')),
                ('payment_method', models.CharField(choices=[(1, 'transfer'), (2, 'cash')], default=1)),
                ('paid_course', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='project.course', verbose_name='оплаченный курс')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'Платеж',
                'verbose_name_plural': 'Платежи',
            },
        ),
    ]
