# Generated by Django 4.2.7 on 2023-12-10 20:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_alter_payment_payment_date_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.IntegerField(blank=True, default=1000, null=True, verbose_name='Цена курса'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 12, 10, 20, 18, 33, 477636, tzinfo=datetime.timezone.utc), null=True, verbose_name='дата оплаты'),
        ),
    ]
