# Generated by Django 4.2.7 on 2023-12-17 13:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0013_alter_payment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.IntegerField(default=1000, verbose_name='сумма платежа'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 12, 17, 13, 27, 41, 601288, tzinfo=datetime.timezone.utc), null=True, verbose_name='дата оплаты'),
        ),
    ]
