# Generated by Django 4.2.7 on 2023-12-26 01:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0017_alter_payment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 12, 26, 1, 0, 16, 516871, tzinfo=datetime.timezone.utc), null=True, verbose_name='дата оплаты'),
        ),
    ]
